FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["RecipeAPI/RecipeAPI.csproj", "RecipeAPI/"]
COPY ["Core/Core.csproj", "Core/"]
RUN dotnet restore "RecipeAPI/RecipeAPI.csproj"
COPY . .
WORKDIR "/src/RecipeAPI"
RUN dotnet build "RecipeAPI.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "RecipeAPI.csproj" -c Release -o /app --no-restore --no-build

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "RecipeAPI.dll"]