FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["Website/Website.csproj", "Website/"]
COPY ["Core/Core.csproj", "Core/"]
RUN dotnet build "Core/Core.csproj" -c Release
COPY . .

WORKDIR "/src/Core"
RUN dotnet build "Core.csproj" -c Release -o /app

WORKDIR "/src/Website"

FROM build AS publish
RUN dotnet publish "Website.csproj" -c Release -o /app 

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Website.dll"]