FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Website/Website.csproj", "Website/"]
COPY ["Core/Core.csproj", "Core/"]
RUN dotnet restore "Website/Website.csproj"
COPY . .

WORKDIR "/src/Core"
RUN dotnet build "Core.csproj" -c Release -o /app -r linux-arm64 /p:Platform="Any CPU"

WORKDIR "/src/Website"
RUN dotnet build "Website.csproj" -c Release -o /app -r linux-arm64 /p:Platform="Any CPU"

FROM build AS publish
RUN dotnet publish "Website.csproj" -c Release -o /app/publish -r linux-arm64 /p:Platform="Any CPU"

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Website.dll"]
