name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore RecipeApp/Website.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore RecipeApp/Website.sln
    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release --verbosity normal RecipeApp/Website.sln --filter Category!=Integration
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.2
