# This is a basic workflow to help you get started with Actions

name: Sonar Dotnet Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Sonarscanner for dotnet
      uses: Secbyte/dotnet-sonarscanner@v2.2
      with:
        buildCommand: dotnet build  RecipeApp/Website.sln
        testCommand: dotnet test RecipeApp/Website.sln --verbosity Normal --filter Category!=Integration  --collect:"XPlat Code Coverage"  
        projectKey: gh_alexa_recipe_app
        projectName: Github Alexa Recipe App
        sonarOrganisation: queen-of-code-github
        beginArguments: >
            /d:sonar.verbose="true"
            /d:sonar.cs.cobertura.reportsPaths='"**/coverage.cobertura.xml"'
            /d:sonar.coverage.exclusions='"RecipeApp/tests/**/*.cs","**/*.md"'
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
